spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    name: test
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.bean
server:
  port: 8081
  servlet:
    context-path: /demo/